DROP TABLE IF EXISTS person;
CREATE TABLE person (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  version VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
